version: '3.7'
services:

  local:
    build:
      context: .
      dockerfile: ./Dockerfile.local

    environment:
      - TARGET_USER=pg
      - TARGET_PASSWORD=pg
      - TARGET_DATABASE=pgdatabase
      - TARGET_PORT=5430
      - TARGET_HOST=target
      - SOURCE_USER=pg
      - SOURCE_PASSWORD=pg
      - SOURCE_DATABASE=pgdatabase
      - SOURCE_PORT=5431
      - SOURCE_HOST=source
    volumes:
      - ./src:/src
    networks:
      - trino-network


  dbt:
    build:
      context: .
      dockerfile: ./Dockerfile.dbt
    hostname: dbt
    volumes:
      - ./dbt:/dbt
    environment:
      - DBT_PROFILES_DIR=/dbt
      - DBT_PROJECT_DIR=/dbt
    networks:
      - trino-network

  cluster:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino
    networks:
      - trino-network

  target:
    image: postgres:latest
    hostname: target
    ports:
      - '5430:5430'
    environment:
      - POSTGRES_PASSWORD=pg
      - POSTGRES_USER=pg
      - POSTGRES_DB=pgdatabase
      - PGPORT=5430
    networks:
      - trino-network

  source:
    image: postgres:latest
    hostname: source
    ports:
      - '5431:5431'
    environment:
      - POSTGRES_PASSWORD=pg
      - POSTGRES_USER=pg
      - POSTGRES_DB=pgdatabase
      - PGPORT=5431
    networks:
      - trino-network

networks:
  trino-network:
    driver: bridge
